name: |
  Sync page images from GitHub CDN

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: write

jobs:
  image-sync:
    name: Sync GitHub CDN images in pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: 'pip'
          cache-dependency-path: 'tools/requirements.txt'

      - name: Install dependencies
        id: deps
        run: |
          pip install -r tools/requirements.txt

      - name: Sync images
        id: image-sync
        run: |
          sudo python3 tools/image-sync.py .

      - name: Commit changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Sync Images Workflow'
            git config --global user.email 'headphonegits-workflows@users.noreply.github.com'
            git add -A
            git commit -m "sync images"
            git push
          fi
